;; A simple major mode for editing SNOPT specs files
;;
;;
;; By C. E. Mower, 2020.
;;

(setq snopt-specs-mode-highlights
      '(("BEGIN\\|Begin\\|END\\|End" . font-lock-keyword-face)
	("Yes\\|yes\\|No\\|no" . font-lock-string-face)
	("Cholesky\\|cholesky" . font-lock-string-face)
	("lencw\\|leniw\\|lenrw" . font-lock-string-face)
	("full memory\\|limited memory" . font-lock-string-face)
	("Major print level\\|major print level" . font-lock-builtin-face)
	("Minor print level\\|minor print level" . font-lock-builtin-face)
	("Print frequency\\|print frequency" . font-lock-builtin-face)
	("Summary frequency\\|summary frequency" . font-lock-builtin-face)
	("Solution\\|solution" . font-lock-builtin-face)
	("System information\\|system information" . font-lock-builtin-face)
	("Minimize\\|minimize" . font-lock-builtin-face)
	("Maximize\\|maximize" . font-lock-builtin-face)
	("Objective row\\|objective row" . font-lock-builtin-face)
	("Infinite bound\\|infinite bound" . font-lock-builtin-face)
	("Major feasibility tolerance\\|major feasibility tolerance" . font-lock-builtin-face)
	("Major optimality tolerance\\|major optimality tolerance" . font-lock-builtin-face)
	("Minor feasibility tolerance\\|minor feasibility tolerance" . font-lock-builtin-face)
	("Verify level\\|verify level" . font-lock-builtin-face)
	("Start objective check at col\\|start objective check at col" . font-lock-builtin-face)
	("Stop objective check at col\\|stop objective check at col" . font-lock-builtin-face)
	("Start constraint check at col\\|start constraint check at col" . font-lock-builtin-face)
	("Stop constraint check at col\\|stop constraint check at col" . font-lock-builtin-face)
	("Scale option\\|scale option" . font-lock-builtin-face)
	("Scale tolerance\\|scale tolerance" . font-lock-builtin-face)
	("Scale print\\|scale print" . font-lock-builtin-face)
	("Crash tolerance\\|crash tolerance" . font-lock-builtin-face)
	("Linesearch tolerance\\|linesearch tolerance" . font-lock-builtin-face)
	("Pivot tolerance\\|pivot tolerance" . font-lock-builtin-face)
	("QPSolver\\|QPsolver\\|qpsolver" . font-lock-builtin-face)
	("Crash option\\|crash option" . font-lock-builtin-face)
	("Elastic weight\\|elastic weight" . font-lock-builtin-face)
	("Iterations limit\\|iterations limit" . font-lock-builtin-face)
	("Partial price\\|partial price" . font-lock-builtin-face)
	("Time limit" . font-lock-builtin-face)
	("Major iterations limit\\|major iterations limit" . font-lock-builtin-face)
	("Minor iterations limit\\|minor iterations limit" . font-lock-builtin-face)
	("Major step limit\\|major step limit" . font-lock-builtin-face)
	("Superbasics limit\\|superbasics limit" . font-lock-builtin-face)
	("Derivative level\\|derivative level" . font-lock-builtin-face)
	("Derivative option\\|derivative option" . font-lock-builtin-face)
	("Derivative linesearch\\|derivative linesearch" . font-lock-builtin-face)
	("Function precision\\|function precision" . font-lock-builtin-face)
	("Difference interval\\|difference interval" . font-lock-builtin-face)
	("Central difference interval\\|central difference interval" . font-lock-builtin-face)
	("New superbasics limit\\|new superbasics limit" . font-lock-builtin-face)
	("Objective row\\|objective row" . font-lock-builtin-face)
	("Penalty parameter\\|penalty parameter" . font-lock-builtin-face)
	("Proximal point method\\|proximal point method" . font-lock-builtin-face)
	("Reduced Hessian dimension\\|reduced hessian dimension" . font-lock-builtin-face)
	("Violation limit\\|violation limit" . font-lock-builtin-face)
	("Unbounded step size\\|unbounded step size" . font-lock-builtin-face)
	("Unbounded objective\\|unbounded objective" . font-lock-builtin-face)
	("Hessian\\|hessian" . font-lock-builtin-face)
	("Hessian frequency\\|hessian frequency" . font-lock-builtin-face)
	("Hessian updates\\|hessian updates" . font-lock-builtin-face)
	("Hessian flush\\|hessian flush" . font-lock-builtin-face)
	("Check frequency\\|check frequency" . font-lock-builtin-face)
	("Expand frequency\\|expand frequency" . font-lock-builtin-face)
	("Factorization frequency\\|factorization frequency" . font-lock-builtin-face)
	("Save frequency\\|save frequency" . font-lock-builtin-face)
	("LU factor tolerance\\|lu factor tolerance" . font-lock-builtin-face)
	("LU update tolerance\\|lu update tolerance" . font-lock-builtin-face)
	("LU singularity tolerance\\|lu singularity tolerance" . font-lock-builtin-face)
	("LU partial pivoting\\|lu partial pivoting" . font-lock-builtin-face)
	("LU rook pivoting\\|lu rook pivoting" . font-lock-builtin-face)
	("LU complete pivoting\\|lu complete pivoting" . font-lock-builtin-face)
	("Old basis file\\|old basis file" . font-lock-builtin-face)
	("New basis file\\|new basis file" . font-lock-builtin-face)
	("Backup basis file\\|backup basis file" . font-lock-builtin-face)
	("Insert file\\|insert file" . font-lock-builtin-face)
	("Punch file\\|punch file" . font-lock-builtin-face)
	("Load file\\|load file" . font-lock-builtin-face)
	("Dump file\\|dump file" . font-lock-builtin-face)
	("Solution file\\|solution file" . font-lock-builtin-face)
	("Total character workspace\\|total character workspace" . font-lock-builtin-face)
	("Total integer workspace\\|total integer workspace" . font-lock-builtin-face)
	("Total real workspace\\|total real workspace" . font-lock-builtin-face)
	("User character workspace\\|user character workspace" . font-lock-builtin-face)
	("User integer workspace\\|user integer workspace" . font-lock-builtin-face)
	("User real workspace\\|user real workspace" . font-lock-builtin-face)
	("Debug level\\|debug level" . font-lock-builtin-face)
	("Sticky parameters\\|sticky parameters" . font-lock-builtin-face)
	("Timing level\\|timing level" . font-lock-builtin-face)))

(defvar snopt-specs-mode-syntax-table nil "Syntax table for `snopt-specs-mode'.")

(setq snopt-specs-mode-syntax-table
      (let ( (synTable (make-syntax-table)))
        ;; * is comment
        (modify-syntax-entry ?* "<" synTable)
        (modify-syntax-entry ?\n ">" synTable)
        synTable))

(define-derived-mode snopt-specs-mode fundamental-mode "snopt-specs"
  "major mode for editing SNOPT Specs files."
  (setq font-lock-defaults '(snopt-specs-mode-highlights)))

(add-to-list 'auto-mode-alist '("\\.spc\\'" . snopt-specs-mode))
